export enum Project {
  AEVO = "aevo",
  AEVO_TESTNET = "aevo-testnet",
  LYRA_TESTNET = "lyra-testnet",
  LYRA = "lyra",
  SX_NETWORK_TESTNET = "sx-network-testnet",
  LEAF_TESTNET = "leaf-testnet",
  SAND_TESTNET = "sand-testnet",
  SOUND_TESTNET = "sound-testnet",
  RAIN_TESTNET = "rain-testnet",
  MIST_TESTNET = "mist-testnet",
  REYA_CRONOS = "reya-cronos",
  REYA = "reya",
  SPECTRAL_SIGNAL = "spectral-signal",
  BOBO = "bobo",
}
