export enum Project {
  AEVO = "aevo",
  AEVO_TESTNET = "aevo-testnet",
  LYRA_TESTNET = "lyra-testnet",
  LYRA = "lyra",
  SX_NETWORK_TESTNET = "sx-network-testnet",
  LEAF_TESTNET = "leaf-testnet",
  RAIN_TESTNET = "rain-testnet",
  MIST_TESTNET = "mist-testnet",
  REYA_CRONOS = "reya-cronos",
  REYA = "reya",
  SPECTRAL_SIGNAL = "spectral-signal",
  SYNDR_SEPOLIA_TESTNET = "syndr_sepolia_testnet",
  TESTING_MAINNET = "testing_mainnet",
  AA_MAINNET = "aa_mainnet",
  SV_MAINNET = "sv_mainnet",
  ADG_MAINNET = "adg_mainnet",
  AAVEGOTCHI_MAINNET = "aavegotchi_mainnet",
  TIMESWAP_TEST_MAINNET = "timeswap_test_mainnet",
  TESTING_TESTNET = "testing_testnet",
}
