import { ChainSlug } from "@socket.tech/dl-core";

export const rpcKeys = {
  [ChainSlug.AEVO]: "AEVO_RPC",
  [ChainSlug.ARBITRUM]: "ARBITRUM_RPC",
  [ChainSlug.LYRA]: "LYRA_RPC",
  [ChainSlug.OPTIMISM]: "OPTIMISM_RPC",
  [ChainSlug.BSC]: "BSC_RPC",
  [ChainSlug.POLYGON_MAINNET]: "POLYGON_RPC",
  [ChainSlug.MAINNET]: "ETHEREUM_RPC",
  [ChainSlug.HOOK]: "HOOK_RPC",
  [ChainSlug.MANTLE]: "MANTLE_RPC",
  [ChainSlug.REYA]: "REYA_RPC",
  [ChainSlug.ARBITRUM_SEPOLIA]: "ARBITRUM_SEPOLIA_RPC",
  [ChainSlug.OPTIMISM_SEPOLIA]: "OPTIMISM_SEPOLIA_RPC",
  [ChainSlug.SEPOLIA]: "SEPOLIA_RPC",
  [ChainSlug.AEVO_TESTNET]: "AEVO_TESTNET_RPC",
  [ChainSlug.LYRA_TESTNET]: "LYRA_TESTNET_RPC",
  [ChainSlug.BSC_TESTNET]: "BSC_TESTNET_RPC",
  [ChainSlug.SX_NETWORK_TESTNET]: "SX_NETWORK_TESTNET_RPC",
  [ChainSlug.SX_NETWORK]: "SX_NETWORK_RPC",
  [ChainSlug.BASE]: "BASE_RPC",
  [ChainSlug.HOOK_TESTNET]: "HOOK_TESTNET_RPC",
  [ChainSlug.REYA_CRONOS]: "REYA_CRONOS_RPC",
  [ChainSlug.SYNDR_SEPOLIA_L3]: "SYNDR_SEPOLIA_L3_RPC",
  [ChainSlug.POLYNOMIAL_TESTNET]: "POLYNOMIAL_TESTNET_RPC",
  [ChainSlug.CDK_TESTNET]: "CDK_TESTNET_RPC",
};
