export enum Tokens {
  Moon = "MOON",
  USDCE = "USDC.e",
  USDC = "USDC",
  WETH = "WETH",
  WBTC = "WBTC",
  USDT = "USDT",
  SNX = "SNX",
  WSTETH = "wstETH",
  DAI = "DAI",
  GUARD = "GUARD",
  ETH = "ETH",
  MTK = "MTK",
  FUD = "FUD",
  FOMO = "FOMO",
  ALPHA = "ALPHA",
  KEK = "KEK",
  GLTR = "GLTR",
  STIME = "STIME",
}
