import { Tokens } from "./tokens";

export const tokenDecimals: { [key in Tokens]: number } = {
  [Tokens.Moon]: 18,
  [Tokens.USDC]: 6,
  [Tokens.USDCE]: 6,
  [Tokens.WETH]: 18,
  [Tokens.WBTC]: 8,
  [Tokens.USDT]: 6,
  [Tokens.SNX]: 18,
  [Tokens.WSTETH]: 18,
  [Tokens.DAI]: 18,
  [Tokens.GUARD]: 18,
  [Tokens.ETH]: 18,
  [Tokens.EIGEN]: 18,
  [Tokens.ENA]: 18,
  [Tokens.USDe]: 18,
  [Tokens.eETH]: 18,
  [Tokens.sDAI]: 18,
  [Tokens.sUSDe]: 18,
  [Tokens.wUSDM]: 18,
  [Tokens.weETH]: 18,
  [Tokens.ETHFI]: 18,
  [Tokens.SolvBTC]: 18,
  [Tokens.KINTO]: 18,
};
