export enum Tokens {
  Moon = "MOON",
  USDCE = "USDC.e",
  USDC = "USDC",
  WETH = "WETH",
  WBTC = "WBTC",
  USDT = "USDT",
  SNX = "SNX",
  WSTETH = "wstETH",
  DAI = "DAI",
  GUARD = "GUARD",
  ETH = "ETH",
  TESTOKEN = "TESTOKEN",
  TOKEN1 = "TOKEN1",
  TEST2 = "TEST2",
  TEST3 = "TEST3",
  PEPE = "PEPE",
}
