import { Tokens } from "./tokens";

export const tokenSymbol: { [key in Tokens]: string } = {
  [Tokens.Moon]: "MOON",
  [Tokens.USDCE]: "USDC.e",
  [Tokens.USDC]: "USDC",
  [Tokens.WETH]: "WETH",
  [Tokens.WBTC]: "WBTC",
  [Tokens.USDT]: "USDT",
  [Tokens.SNX]: "SNX",
  [Tokens.WSTETH]: "wstETH",
  [Tokens.DAI]: "DAI",
  [Tokens.GUARD]: "GUARD",
  [Tokens.ETH]: "ETH",
  [Tokens.EIGEN]: "EIGEN",
  [Tokens.ENA]: "ENA",
  [Tokens.USDe]: "USDe",
  [Tokens.eETH]: "eETH",
  [Tokens.sDAI]: "sDAI",
  [Tokens.sUSDe]: "sUSDe",
  [Tokens.wUSDM]: "wUSDM",
  [Tokens.weETH]: "weETH",
  [Tokens.ETHFI]: "ETHFI",
  [Tokens.SolvBTC]: "SolvBTC",
  [Tokens.KINTO]: "KINTO",
  [Tokens.MKR]: "MKR",
  [Tokens.PAXG]: "PAXG",
  [Tokens.XAUT]: "XAUT",
  [Tokens.eUSD]: "eUSD",
  [Tokens.rsENA]: "rsENA",
  [Tokens.rsUSDe]: "rsUSDe",
  [Tokens.stUSD]: "stUSD",
  [Tokens.stEUR]: "stEUR",
  [Tokens.SOL]: "SOL",
  [Tokens.SPX]: "SPX",
};
