export enum Tokens {
  USDCE = "USDC.e",
  USDC = "USDC",
  USDT = "USDT",
  DAI = "DAI",
  WETH = "WETH",
  ETH = "ETH",
  WSTETH = "wstETH",
  WBTC = "WBTC",
  SNX = "SNX",
  GUARD = "GUARD",
  MTK = "MTK",
  FUD = "FUD",
  FOMO = "FOMO",
  ALPHA = "ALPHA",
  KEK = "KEK",
  GLTR = "GLTR",
  STIME = "STIME",
  Moon = "MOON",
  USDE = "USDe",
  MAGIC = "MAGIC",
  SUSDE = "SUSDE",
  SDEUSD = "SDEUSD",
  DEUSD = "DEUSD",
  SGHST = "SGHST",
}
